spring:
  profiles:
    active: test
---
spring:
  profiles: test
  application:
    name: config-test
server:
  port: 8010
---
spring:
  profiles: prod
  application:
    name: config-prod
server:
  port: 8012
