spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cluo1/super.git
          username: cluo1
          password: ln37807090
      label: master
server:
  port: 8001

